import { createSlice } from "@reduxjs/toolkit";

// Initial state for the cart slice
const initialState = {
  items: [],
};

// Create a slice of state named 'cart'
const cartSlice = createSlice({
  name: "cart", // Name of the slice
  initialState, // Initial state of the slice
  reducers: {
    // Reducer to add an item to the cart
    addItem: (state, action) => {
      state.items.push(action.payload);
    },
  },
});

// Export the actions generated by createSlice
export const { addItem } = cartSlice.actions;

// Export the reducer to be included in the store
export default cartSlice.reducer;
